spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: adm
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect